import React, { useState, useEffect } from "react";
import AddCategoryModal from "../components/AddCategoryModal";
import Head from "next/head";

import {
  openCategoryModal,
  closeCategoryModal,
  openLocationModal,
  closeLocationModal,
  selectCategoryModalIsOpen,
  selectLocationModalIsOpen,
} from "../features/modalSlice";
import { sanityClient, urlFor } from "../sanity";
import AddLocationModal from "../components/AddLocationModal";
import { AiOutlinePlusCircle, AiOutlineClose } from "react-icons/ai";
import AddPost from "../components/AddPost";
import { useDispatch, useSelector } from "react-redux";
import AdminPostList from "../components/AdminPostList";
import AddPostCategories from "../components/AddPostCategories";
import { fetchPost } from "../utils/fetchpost";
import AddImagetoPost from "../components/AddImagetoPost";

function Admin({ location, categories, posts }) {
  const dispatch = useDispatch();
  const [phase, setPhase] = useState("Post");
  const [selectPost, setSelectPost] = useState(null);
  const [refetchpost, setRefetchPost] = useState(posts);

  const locationModalisOpen = useSelector(selectLocationModalIsOpen);
  const categoryModalisOpen = useSelector(selectCategoryModalIsOpen);

  const Phase = ({ name, isActive, setPhase }) => {
    return (
      <div
        onClick={() => setPhase(name)}
        className={`flex flex-col items-center cursor-pointer`}
      >
        <h1
          className={`font-bold ${
            isActive ? "text-gray-800" : "text-gray-400"
          }`}
        >
          {name}
        </h1>
        <div
          className={`w-4 h-4 rounded-full ${
            isActive ? "bg-blue-600" : "bg-gray-400"
          }`}
        />
      </div>
    );
  };

  const fetchsome = async () => {
    const query = `*[_type == "post"]{
      _id,
      title,
      author->{
        _id,
        ...,
      },
      slug,
      publishedAt,
      categories[]->{
        ...,
      },
      mainImage,
      location->{
        ...,
      },
    }`;
    const posts = await sanityClient.fetch(query);
    console.log(posts);
  };

  return (
    <div className="flex flex-col h-screen max-h-screen">
      <Head>
        <title>Zong Hong PhotoTravel Map Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={fetchsome}>fetch</button>
      <div className="mb-4 flex justify-evenly mt-10">
        <Phase
          setPhase={setPhase}
          name="Post"
          isActive={phase == "Post" ? true : false}
        />
        <Phase
          setPhase={setPhase}
          name="AddPost"
          isActive={phase == "AddPost" ? true : false}
        />
        <Phase
          setPhase={setPhase}
          name="AddImage"
          isActive={phase == "AddImage" ? true : false}
        />
        <Phase
          setPhase={setPhase}
          name="AddPostCategory"
          isActive={phase == "AddPostCategory" ? true : false}
        />
      </div>
      <main className="h-screen">
        {phase == "Post" && (
          <AdminPostList
            posts={posts}
            setSelectPost={setSelectPost}
            selectPost={selectPost}
          />
        )}
        {phase == "AddPost" && (
          <AddPost location={location} categories={categories} />
        )}
        {phase == "Add" && (
          <AddPost location={location} categories={categories} />
        )}
        {phase == "AddImage" && (
          <AddImagetoPost selectPost={selectPost} setPhase={setPhase} />
        )}
        {phase == "AddPostCategory" && (
          <AddPostCategories
            setPhase={setPhase}
            selectPost={selectPost}
            categories={categories}
          />
        )}
      </main>

      {locationModalisOpen && <AddLocationModal />}
      {categoryModalisOpen && <AddCategoryModal />}
    </div>
  );
}
export default Admin;
export const getServerSideProps = async (context) => {
  const query = `*[_type == "post"]{
    _id,
    title,
    author->{
      _id,
      ...,
    },
    slug,
    publishedAt,
    categories[]->{
      ...,
    },
    mainImage,
    location->{
      ...,
    },
  }`;

  const locationquery = `*[_type == "location"]{
     ...
    }`;
  const categoriesquery = `*[_type == "category"]{
        ...
       }`;
  const posts = await sanityClient.fetch(query);
  const location = await sanityClient.fetch(locationquery);
  const categories = await sanityClient.fetch(categoriesquery);

  return {
    props: {
      posts,
      location,
      categories,
    },
  };
};
